// AUTO-GENERATED by simulink-mini CodeGen. Do not edit by hand.
// Model: GeneratedModel -- compiled with 4 blocks, 2 state variable(s).
#include <cstdio>
#include <cmath>

constexpr int STATE_SIZE = 2;

// Forward pass computes every block's instantaneous output in
// valid execution order, then extracts the derivative feeding each
// stateful (Integrator) block from its already-computed input.
void computeDerivatives(const double state[STATE_SIZE], double deriv[STATE_SIZE]) {
    double out_int_v = state[0]; // Integrator output = state
    double out_int_x = state[1]; // Integrator output = state
    double out_gain_a = -4 * out_int_x; // Gain
    double out_scope_x = out_int_x; // Scope (pass-through)

    // Derivative for each stateful (Integrator) block = its input.
    deriv[1] = out_int_v; // d/dt of int_x
    deriv[0] = out_gain_a; // d/dt of int_v
}

int main() {
    double state[STATE_SIZE] = {0, 1};
    const double dt = 0.001, tEnd = 10.0;
    const int steps = (int)(tEnd / dt);
    double k1[STATE_SIZE], k2[STATE_SIZE], k3[STATE_SIZE], k4[STATE_SIZE], tmp[STATE_SIZE];

    for (int i = 0; i <= steps; ++i) {
        double t = i * dt;
        std::printf("%.6f,%.10f\n", t, state[1]);
        if (i == steps) break;
        computeDerivatives(state, k1);
        for (int j = 0; j < STATE_SIZE; ++j) tmp[j] = state[j] + dt/2.0 * k1[j];
        computeDerivatives(tmp, k2);
        for (int j = 0; j < STATE_SIZE; ++j) tmp[j] = state[j] + dt/2.0 * k2[j];
        computeDerivatives(tmp, k3);
        for (int j = 0; j < STATE_SIZE; ++j) tmp[j] = state[j] + dt * k3[j];
        computeDerivatives(tmp, k4);
        for (int j = 0; j < STATE_SIZE; ++j)
            state[j] += (dt/6.0) * (k1[j] + 2*k2[j] + 2*k3[j] + k4[j]);
    }
    return 0;
}
