#pragma once
#include "Graph.hpp"
#include "Simulation.hpp"
#include <sstream>
#include <iomanip>

namespace simmini {

// ---------------------------------------------------------------------------
// CodeGen emits a standalone .cpp file that implements computeDerivatives()
// for one SPECIFIC compiled diagram, with every block's output unrolled into
// a named local variable in execution order -- exactly the "compile the
// model, don't interpret it" approach real code generators (e.g. Simulink's
// Embedded Coder) take, so the emitted code can be inspected, reviewed, and
// flashed to a target with no runtime graph-walking overhead at all.
// ---------------------------------------------------------------------------
class CodeGen {
public:
    static std::string generate(const Graph& g,
                                 const std::vector<std::string>& order,
                                 const Simulation& sim,
                                 const std::string& modelName = "GeneratedModel") {
        const auto& stateIndex = sim.stateIndexMap();
        const int stateSize = sim.stateSize(); // NOT stateIndex.size() -- PID uses 2 slots per block
        std::ostringstream out;

        out << "// AUTO-GENERATED by simulink-mini CodeGen. Do not edit by hand.\n";
        out << "// Model: " << modelName << " -- compiled with " << g.numBlocks() << " blocks, "
            << stateSize << " state variable(s).\n";
        out << "#include <cstdio>\n#include <cmath>\n\n";
        out << "constexpr int STATE_SIZE = " << stateSize << ";\n\n";

        // --- computeDerivatives: the unrolled forward pass + derivative extraction ---
        out << "// Forward pass computes every block's instantaneous output in\n"
               "// valid execution order, then extracts the derivative feeding each\n"
               "// stateful block (Integrator: 1 state slot; PID: 2 -- integral +\n"
               "// filtered-derivative state) from its already-computed input.\n";
        out << "void computeDerivatives(const double state[STATE_SIZE], double deriv[STATE_SIZE]) {\n";

        for (auto& id : order) {
            const Block& b = g.block(id);
            std::string var = "out_" + sanitize(id);

            switch (b.type) {
                case BlockType::Constant:
                    out << "    double " << var << " = " << fmt(Simulation::getParam(b, "value", 0.0))
                        << "; // Constant\n";
                    break;
                case BlockType::Integrator:
                    out << "    double " << var << " = state[" << stateIndex.at(id)
                        << "]; // Integrator output = state\n";
                    break;
                case BlockType::Gain: {
                    std::string in = inputVar(g, id, 0);
                    out << "    double " << var << " = " << fmt(Simulation::getParam(b, "k", 1.0))
                        << " * " << in << "; // Gain\n";
                    break;
                }
                case BlockType::Sum: {
                    int n = Simulation::expectedNumInputs(b);
                    out << "    double " << var << " = ";
                    for (int i = 0; i < n; ++i) {
                        char sign = (i < (int)b.inputSigns.size()) ? b.inputSigns[i][0] : '+';
                        out << (sign == '-' ? " - " : (i == 0 ? "" : " + ")) << inputVar(g, id, i);
                    }
                    out << "; // Sum\n";
                    break;
                }
                case BlockType::Product: {
                    int n = Simulation::expectedNumInputs(b);
                    out << "    double " << var << " = ";
                    for (int i = 0; i < n; ++i) {
                        out << (i == 0 ? "" : " * ") << inputVar(g, id, i);
                    }
                    out << "; // Product\n";
                    break;
                }
                case BlockType::PID: {
                    // out = Kp*e + Ki*I + Kd*(e - Df)/Tf
                    // I  = state[base]   (integral accumulator)
                    // Df = state[base+1] (filtered-derivative state)
                    int base = stateIndex.at(id);
                    std::string e = inputVar(g, id, 0);
                    double Kp = Simulation::getParam(b, "Kp", 1.0);
                    double Ki = Simulation::getParam(b, "Ki", 0.0);
                    double Kd = Simulation::getParam(b, "Kd", 0.0);
                    double Tf = Simulation::getParam(b, "Tf", 0.01);
                    out << "    double " << var << " = " << fmt(Kp) << " * " << e
                        << " + " << fmt(Ki) << " * state[" << base << "]"
                        << " + " << fmt(Kd) << " * (" << e << " - state[" << (base + 1) << "]) / " << fmt(Tf)
                        << "; // PID\n";
                    break;
                }
                case BlockType::Scope:
                    out << "    double " << var << " = " << inputVar(g, id, 0) << "; // Scope (pass-through)\n";
                    break;
                default:
                    out << "    // NOTE: block type " << blockTypeName(b.type)
                        << " (" << id << ") not supported by CodeGen yet.\n";
                    out << "    double " << var << " = 0.0;\n";
            }
        }

        out << "\n    // Derivatives for every stateful block.\n";
        for (auto& [id, base] : stateIndex) {
            const Block& b = g.block(id);
            if (b.type == BlockType::Integrator) {
                std::string in = inputVar(g, id, 0);
                out << "    deriv[" << base << "] = " << in << "; // d/dt of " << id << "\n";
            } else if (b.type == BlockType::PID) {
                std::string e = inputVar(g, id, 0);
                double Tf = Simulation::getParam(b, "Tf", 0.01);
                out << "    deriv[" << base << "] = " << e << "; // d(integral)/dt of " << id << "\n";
                out << "    deriv[" << (base + 1) << "] = (" << e << " - state[" << (base + 1) << "]) / "
                    << fmt(Tf) << "; // d(filter state)/dt of " << id << "\n";
            }
        }
        out << "}\n\n";

        // --- main(): RK4 loop over computeDerivatives, matching Simulation::stepRK4 exactly ---
        out << "int main() {\n";
        out << "    double state[STATE_SIZE] = {";
        {
            std::vector<double> init(stateSize, 0.0);
            for (auto& [id, base] : stateIndex) {
                const Block& b = g.block(id);
                if (b.type == BlockType::Integrator) {
                    init[base] = Simulation::getParam(b, "initial", 0.0);
                } else if (b.type == BlockType::PID) {
                    init[base] = Simulation::getParam(b, "initial_integral", 0.0);
                    init[base + 1] = 0.0;
                }
            }
            for (size_t i = 0; i < init.size(); ++i) out << (i ? ", " : "") << fmt(init[i]);
        }
        out << "};\n";
        out << "    const double dt = 0.001, tEnd = 10.0;\n";
        out << "    const int steps = (int)(tEnd / dt);\n";
        out << "    double k1[STATE_SIZE], k2[STATE_SIZE], k3[STATE_SIZE], k4[STATE_SIZE], tmp[STATE_SIZE];\n\n";
        out << "    for (int i = 0; i <= steps; ++i) {\n";
        out << "        double t = i * dt;\n";
        out << "        std::printf(\"%.6f,%.10f\\n\", t, state[" << stateIdxOf(stateIndex, g) << "]);\n";
        out << "        if (i == steps) break;\n";
        out << "        computeDerivatives(state, k1);\n";
        out << "        for (int j = 0; j < STATE_SIZE; ++j) tmp[j] = state[j] + dt/2.0 * k1[j];\n";
        out << "        computeDerivatives(tmp, k2);\n";
        out << "        for (int j = 0; j < STATE_SIZE; ++j) tmp[j] = state[j] + dt/2.0 * k2[j];\n";
        out << "        computeDerivatives(tmp, k3);\n";
        out << "        for (int j = 0; j < STATE_SIZE; ++j) tmp[j] = state[j] + dt * k3[j];\n";
        out << "        computeDerivatives(tmp, k4);\n";
        out << "        for (int j = 0; j < STATE_SIZE; ++j)\n";
        out << "            state[j] += (dt/6.0) * (k1[j] + 2*k2[j] + 2*k3[j] + k4[j]);\n";
        out << "    }\n";
        out << "    return 0;\n";
        out << "}\n";

        return out.str();
    }

private:
    static std::string sanitize(const std::string& id) {
        std::string s = id;
        for (auto& c : s) if (!isalnum((unsigned char)c)) c = '_';
        return s;
    }

    static std::string fmt(double v) {
        std::ostringstream oss;
        oss << std::setprecision(17) << v;
        return oss.str();
    }

    // Finds the src block feeding `dstId`'s input slot `slotWanted`, returns its generated var name.
    static std::string inputVar(const Graph& g, const std::string& dstId, int slotWanted) {
        for (auto& [srcId, slot] : g.inEdges(dstId)) {
            if (slot == slotWanted) return "out_" + sanitize(srcId);
        }
        return "0.0";
    }

    // Small helper purely for this project's fixed test diagrams: finds the
    // state slot whose block feeds a Scope, for the demo printout. For a
    // general multi-model tool this would be replaced by an explicit "log
    // this signal" annotation in the JSON schema (a natural Week 4 extension).
    static int stateIdxOf(const std::unordered_map<std::string,int>& stateIndex, const Graph& g) {
        for (auto& [id, base] : stateIndex) {
            for (auto& [dstId, slot] : g.outEdges(id)) {
                (void)slot;
                if (g.block(dstId).type == BlockType::Scope) return base;
            }
        }
        // Fallback: last state slot.
        return stateIndex.empty() ? 0 : (int)stateIndex.size() - 1;
    }
};

} // namespace simmini
